### ISSUE TITLE
RFC 3161 trusted timestamping

### ISSUE THREAD

**Issue by makew0rld** [starlinglab/authenticated-attributes#40]
Test out an implementation of timestamping using [RFC 3161](https://datatracker.ietf.org/doc/html/rfc3161) servers such as the one Digicert [runs](https://knowledge.digicert.com/generalinformation/INFO4231.html). 

One of the important things to check is how the big the stored response is, how much it would inflate attestations.

Also one idea I had is that a modified OpenTimestamps calendar server could possibly use this in the background instead of Bitcoin. That way we could consolidate the code on using OpenTimestamps client.

**Comment by makew0rld** [comment]
There is also [freeTSA](https://freetsa.org/index_en.php) that runs a service. I have personally tested both DigiCert and this one, and the main advantage of DigiCert is that its timestamp signature is done by a cert that can be anchored all the way back to the global browser trust store, which is tracked by CT logs, etc. The freeTSA signature cert is not anchored anywhere and just must be kept around and trusted.

For this reason I recommend we use Digicert if this actually is implemented.

The freeTSA website has some nice example openssl commands for testing though.

---

Verifying RFC 3161 timestamps requires four files:
- The "TimeStampResponse" (.tsr) file from the timestamping server
- The data file (to be hashed to see if the hash matches)
	- Alternatively of course just the hash can be provided
- The untrusted cert that signed the timestamp response. This can be multiple certs (in one file or not) to form a chain.
- The trusted CA cert that is the root of the chain

The .tsr file is the only one that would need to be included with each attestation. The file hash will be calculated by the verifier, and the verifier will also need to gather the certs themselves as part of the verification process.

The .tsr file in my test was 6007 bytes. Adding this would be a significant increase in attestation size, considering a simple attestation is currently 1,177 bytes, including the existing OpenTimestamps section. Whether going from 1.1 KiB to 7 KiB per attestation actually matters to us is another thing.

**Comment by makew0rld** [comment]
- [ ] Link to this comment in README to explain why we didn't use trusted timestamping but how it's still possible

**Comment by makew0rld** [comment]
One last thing: this timestamping method supports not using a nonce.

**Comment by makew0rld** [comment]
Update on this: My understanding of the .tsr file was wrong. If you use `-cert` when generating your request, the returned .tsr file actually includes all the certs you need to verify the request. This goes all the way up to the root CA cert in DigiCert's case, meaning two extra certs from the signing one. This was greatly inflating the .tsr file sizes.

When I don't use `-cert`, the .tsr file only includes the single signing cert, and the final size is 1,131 bytes. This would roughly double the current attestation size, if OTS attestations were kept. But it is much smaller than my original estimate of 6,000 bytes.

A non-upgraded OTS attestation file I made today weighed in at 573 bytes. Sticking with OTS for now still makes sense due to this size difference, and because theoretically OTS can be made to support RFC 3161 in the future ([link](https://petertodd.org/2016/opentimestamps-announcement#timestamp-operation-tree)).

---

My source on this was [here](https://freetsa.org/index_en.php#tcp), click "full example". You can also see this under `-cert` in the `openssl-ts` manpage.

**Comment by petertodd** [comment]
FYI I actually have some hacked together code that uses Roughtime to make trusted timestamps: https://github.com/opentimestamps/restamp

It's not properly integrated into OTS. But I am re-timestamping Bitcoin blocks with it to give a secondary way to validate the time fields within them.

**Comment by makew0rld** [comment]
Interesting, thanks. Internally we've discussed using roughtime, but at the time (Aug 2023) the conclusion was that it wasn't established enough to be useful to us. RFC not finalized, Cloudflare CLI or server didn't seem to work, etc.

**Comment by petertodd** [comment]
Unfortunately I think your conclusion is reasonable. At the moment even Google doesn't even seem to be running a functioning roughtime server. So who knows if it'll get more support in the future.

But I needed something quick and easy for the Guatemalan election timestamping project, and roughtime fit the bill.
