### ISSUE TITLE
Bug: If more than one "supporting file", AA preview doesn't render

### ISSUE THREAD

**Issue by basilesimon** [starlinglab/authenticated-attributes#43]
See for example this entity: https://uwazi.dev.starlinglab.org/en/entity/nglfxgeua8i

https://github.com/starlinglab/authenticated-attributes/blob/main/uwazi/entity-page/src/App.svelte#L122

<img width="1031" alt="image" src="https://github.com/starlinglab/authenticated-attributes/assets/5701152/5becf733-46c7-4624-afab-c9fd2745b189">

**Comment by makew0rld** [comment]
Solution: ignore any files upload with the name `preview` or `preview.*`

**Comment by basilesimon** [comment]
Could we actually ignore all supporting files named `preview.*`?

**Comment by makew0rld** [comment]
Quick fix in main: af6dad299b316ffa2570b372c0dc401b162e8b1b
Full fix in demo2: 8ed2b4a78f0c138514898a4f3529cd687b4584b7
