### ISSUE TITLE
Only upload changed metadata into AA from Uwazi

### ISSUE THREAD

**Issue by makew0rld** [starlinglab/authenticated-attributes#50]
Currently in the metadata-manager service, the entity metadata gets downloaded, compared to the previous submission, and resent in full if it's not an exact much. This means **all** metadata (per-entity) gets re-uploaded if **any** of it has changed, which is a problem because it means the timestamp of old attestations keep shifting. It also increases database size.

Forensically this isn't a problem since the old timestamps are still available due to an append-only log being used. But it's still not the behaviour we want.

- [x] Only update changed metadata
- [x] Persist this behaviour across service restarts

**Comment by basilesimon** [comment]
Alternatively, if the behaviour described above is the one we want, we could also think of "showing the log" in the UI.

**Comment by makew0rld** [comment]
I think keeping timestamps as old as possible without having to dive into the history of the database is probably simpler and more useful.
