### ISSUE TITLE
Encrypt-then-sign

### ISSUE THREAD

**Issue by makew0rld** [starlinglab/authenticated-attributes#55]
Currently the code does **sign-then-encrypt**, where for attestations with encrypted values, the object is signed with the unencrypted value field, then that field is replaced with an encrypted one before being stored in the database. I think it would make sense to switch this to **encrypt-then-sign**.

The main purpose of this change is to allow verifying (possibly exported) attestations are signed by the expected author even if you can't decrypt and read the value. Currently this is not possible.

A usual downside of encrypt-then-sign is that an adversary can take the encrypted value (which they don't know how to decrypt) and replace the signature, as if it was their own. For our purposes I don't think this is a big issue.

The other downside of this is it will require breaking all old databases (*only for encrypted values*), as nothing is versioned and this is a breaking change. I think this is fine since we haven't seen real usage of encrypted values yet, although it does raise the question of if we need to add versioning going forward.

@benhylau hoping you can review and approve this.

**Comment by benhylau** [comment]
My concern would be that if the key got leaked and we have to rotate the sym password, the attestation sig will be lost. I am attesting to the pre-encrypted info, not the encryption layer.

But I also see value in verifying all data in a sync, encrypted or not.

**Comment by makew0rld** [comment]
That's a good point. I guess one solution would be to sign things twice for encrypted values. I'll look more into this.

What prompted this issue was the realization that the export proof tool (among others) wouldn't be able to export encrypted attestations without the encryption key being provided as well, and without it being provided over the network to AA. That seemed unnecessary which is what got me thinking here, but maybe in the end it's fine and we'll live with it, so we can get the protection you mentioned.

-------- Original Message --------

**Comment by benhylau** [comment]
Actually what you really want to do is to do a blind signature, where you encrypt-then-sign but the signature is verifiable against the original pre-encrypted text.

https://en.wikipedia.org/wiki/Blind_signature

**Comment by makew0rld** [comment]
From some quick research it looks like blind signatures are used mainly for situations when you want a party that is not the author to sign something, which doesn't apply here. I am also unable to find any sources that confirm that "EC Blind Schnorr Signature scheme" allows verifying a ciphertext and plaintext at the same time.

For now I think we can leave things as they are, sign-then-encrypt. At least at a lower level everything is still signed by the Hypercore key.

**Comment by makew0rld** [comment]
I think we can conclude using sign-then-encrypt is fine.
